import { StyleSheet } from 'aphrodite/no-important';

export default StyleSheet.create({
    Top:{
        paddingTop:25,
        paddingBottom:25,
        marginTop:-15
    },
    topOne:{
        margin:0,
        fontSize:14,
        color:'#ffffff',
        textAlign:'center',
        fontFamily:'GothamPro-Bold'
    },
    topTwo:{
        margin:0,
        color:'#d94738',
        textAlign:'center',
        fontSize:27,
        fontFamily:'GothamPro-Bold'
    },
    topThree:{
        fontSize:14,
        color:'#ffffff',
        textAlign:'center',
        marginTop:4,
        marginBottom:0
    },
    item:{
        width: 'calc(100% + 30px)',
        marginLeft:-15,
        height:100,
        background:'#2c2c2c',
        borderLeft:'4px solid #e04939'
    },
    itemLeft:{
        width:'30%',
        height:100,
        float:'left',
        position:'relative'
    },
    itemRight:{
        width:'70%',
        height:100,
        float:'right',
    },
    itemLeftImg:{
        display:'block',
        width:'75%',
        margin:'auto',
        position:'absolute',
        top:0,
        bottom:0,
        left:0,
        right:0
    },
    sity:{
        fontSize:11,
        color:'#ffffff',
        fontFamily:'GothamPro-Medium',
        marginBottom:0,
        marginTop:12
    },
    addres:{
        fontSize:16,
        color:'#ffffff',
        fontFamily:'GothamPro-Medium',
        marginTop:0,
        marginBottom:5
    },
    addMap:{
        fontSize:13,
        color:'#ffffff',
        fontFamily:'GothamPro-Medium',
        padding:'5px 15px',
        borderRadius:4,
        border:'1px solid #ffffff'
    },
    itemPhone:{
        width: 'calc(100% + 30px)',
        paddingLeft:15,
        paddingRight:15,
        marginLeft:-15,
        height:100,
        borderBottom:'1px solid #3c3c3c'
    },
    itemPhoneLeft:{
        width:'50%',
        float:'left',
        height:100
    },
    itemPhoneRight:{
        width:'50%',
        float:'left',
        height:100
    },
    itemPhoneText:{
        fontFamily:'GothamPro-Medium',
        fontSize:12,
        color:'#ffffff',
        marginTop:25
    },
    itemPhoneSpan:{
        fontSize:17,
        display:'block',
        marginTop:8
    },
    itemPhoneButton:{
        fontSize:13,
        color:'#ffffff',
        padding:'5px 10px',
        background:'#d44536',
        border:0,
        fontFamily:'GothamPro-Medium',
        borderRadius:4,
        float:'right',
        marginTop:45
    },
    itemPhoneTextOne:{
        color:'#ffffff',
        fontSize:12,
        marginBottom:6,
        marginTop:17
    },
    itemPhoneTextTwo:{
        color:'#ffffff',
        fontSize:14,
        marginTop:0
    }
})